


function InglesIndex(){

    var Descripcion =  document.getElementById('Descripcion')
    var Puyehue = document.getElementById('Puyehue')
    var PuyehueD = document.getElementById('PuyehueD')
    var Vicente = document.getElementById('Vicente')
    var VicenteD = document.getElementById('VicenteD')
    var Pumalin = document.getElementById('Pumalin')
    var PumalinD= document.getElementById('PumalinD')

    Descripcion.innerText="We are a page dedicated to the promotion and tourism of Chile's national parks."
    Puyehue.innerText="Puyehue National Park"
    PuyehueD.innerText='You can visit the entire park and see places like"Salto del pudu", the "Casablanca Volcano" and many more places within the park'
    Vicente.innerText="Vicente Perez Rosales National Park"
    VicenteD.innerText='You can visit the entire park and see places like  "Los Enamorados", the "Laguna Verde" and many more places'
    Pumalin.innerText="Pumalin Douglas Tompkins National Park"
    PumalinD.innerText='You can visit the entire park and see places like: "Sendero Punta del Lago", the "Sendero Alerces" and many more places.'

}

function InglesPumalin(){

    var PumalinT = document.getElementById('PumalinT')
    var PumalinDesc= document.getElementById('PumalinDesc')
    var PumalinSub= document.getElementById('PumalinSub')
    var PumalinSub2= document.getElementById('PumalinSub2')
    var PumalinIti= document.getElementById('PumalinIti')
    var Dia= document.getElementById('Dia')
    var Descripcion=document.getElementById('Descripcion')
    var Actividades= document.getElementById('Actividades')
    

    PumalinT.innerText="Pumalin Douglas Tompkins National Park"
    PumalinDesc.innerText="Delve into the virgin nature of Los Pilquenes and marvel at the diversity of flora and fauna that inhabits this natural sanctuary. The Pumalín Douglas Tompkins National Park is much more than a tourist destination, it is a unique experience that will connect you with the beauty and grandeur of nature."
    PumalinSub.innerText="Come and discover the magic. An adventure awaits you on every trail!"
    PumalinSub2.innerText="Take advantage of this unique opportunity to visit this beautiful park! Book your adventure now!"
    PumalinIti.innerText="Schedule"
    Dia.innerText="Day"
    Descripcion.innerText="Description"
    Actividades.innerText="Activities"

    var PumalinD1D=document.getElementById('PumalinD1D')
    var PumalinD1A1=document.getElementById('PumalinD1A1')
    var PumalinD1A2=document.getElementById('PumalinD1A2')
    var PumalinD1A3=document.getElementById('PumalinD1A3')

    PumalinD1D.innerText="Arrival in Puerto Montt and transfer to the park"
    PumalinD1A1.innerText="Reception and transfer from the Puerto Montt airport or your hotel in the city to the Pumalín Douglas Tompkins National Park."
    PumalinD1A2.innerText="Accommodation in a comfortable cabin or lodge within the park."
    PumalinD1A3.innerText="Welcome dinner at a local restaurant."

    var PumalinD2D=document.getElementById('PumalinD2D')
    var PumalinD2A1=document.getElementById('PumalinD2A1')
    var PumalinD2A2=document.getElementById('PumalinD2A2')
    var PumalinD2A3=document.getElementById('PumalinD2A3')
    var PumalinD2A4=document.getElementById('PumalinD2A4')
    var PumalinD2A5=document.getElementById('PumalinD2A5')
    var PumalinD2A6=document.getElementById('PumalinD2A6')

    PumalinD2D.innerText="Exploring Cucao Fjord and Guafo Island"
    PumalinD2A1.innerText="Breakfast at the lodge."
    PumalinD2A2.innerText="Navigation through the Cucao Fjord, a fjord surrounded by imposing mountains and ancient forests."
    PumalinD2A3.innerText="Visit to Guafo Island, an island with a rich biodiversity of flora and fauna."
    PumalinD2A4.innerText="Picnic lunch on the island."
    PumalinD2A5.innerText="In the afternoon, walk along the Alerce Costero trail, a centuries-old larch forest."
    PumalinD2A6.innerText="Dinner and accommodation at the lodge."


    var PumalinD3D=document.getElementById('PumalinD3D')
    var PumalinD3A1=document.getElementById('PumalinD3A1')
    var PumalinD3A2=document.getElementById('PumalinD3A2')
    var PumalinD3A3=document.getElementById('PumalinD3A3')
    var PumalinD3A4=document.getElementById('PumalinD3A4')
    var PumalinD3A5=document.getElementById('PumalinD3A5')
  
    PumalinD3D.innerText="Trekking to Lake Yelcho and La Virgen Waterfall"
    PumalinD3A1.innerText="Breakfast at the lodge"
    PumalinD3A2.innerText="Trekking excursion to Lake Yelcho, a glacial lake with crystal-clear waters and dreamlike landscapes."
    PumalinD3A3.innerText="Lunch in box lunch."
    PumalinD3A4.innerText="In the afternoon, visit La Virgen Waterfall, an imposing waterfall that will leave you breathless."
    PumalinD3A5.innerText="Dinner and accommodation at the lodge."

    var PumalinD4D=document.getElementById('PumalinD4D')
    var PumalinD4A1=document.getElementById('PumalinD4A1')
    var PumalinD4A2=document.getElementById('PumalinD4A2')
    var PumalinD4A3=document.getElementById('PumalinD4A3')
    var PumalinD4A4=document.getElementById('PumalinD4A4')

    PumalinD4D.innerText="Farewell and transfer to Puerto Montt"
    PumalinD4A1.innerText="Breakfast at the lodge"
    PumalinD4A2.innerText="Transfer back to Puerto Montt."
    PumalinD4A3.innerText="Free time for shopping or tourist activities in the city."
    PumalinD4A4.innerText="End of our services."

    var Incluye=document.getElementById('Incluye')
    var Incluye1=document.getElementById('Incluye1')
    var Incluye2=document.getElementById('Incluye2')
    var Incluye3=document.getElementById('Incluye3')
    var Incluye4=document.getElementById('Incluye4')
    var Incluye5=document.getElementById('Incluye5')

    Incluye.innerText="What includes?"
    Incluye1.innerText="Transfers: Reception and transfer from the Puerto Montt airport or your hotel in the city to the Pumalín Douglas Tompkins National Park. Return transfer from the park to Puerto Montt."
    Incluye2.innerText="Accommodation: 3 nights of accommodation in a comfortable cabin or lodge within the park."
    Incluye3.innerText="Food: Breakfast, lunch and dinner throughout the trip (except lunch on the last day). Picnic lunches during excursions."
    Incluye4.innerText="Excursions: Navigation through the Cucao Fjord. Visit to Guafo Island. Walk along the Alerce Costero trail. Trekking to Lake Yelcho. Visit to La Virgen Waterfall."
    Incluye5.innerText="Others: Travel assistance insurance. Specialized guide during all excursions. Entrance fees to the national park. Necessary equipment for excursions (trekking poles, water poncho, etc.)"

    var NoIncluye=document.getElementById('NoIncluye')
    var NoIncluye1=document.getElementById('NoIncluye1')
    var NoIncluye2=document.getElementById('NoIncluye2')
    var NoIncluye3=document.getElementById('NoIncluye3')
    var NoIncluye4=document.getElementById('NoIncluye4')
    var NoIncluye5=document.getElementById('NoIncluye5')

    NoIncluye.innerText="What is not included?"
    NoIncluye1.innerText="Air tickets: Round-trip flights to Puerto Montt are not included in the package price. You can book your flights with the airline of your choice."
    NoIncluye2.innerText="Alcoholic beverages: Alcoholic beverages are not included in meals or picnics. You can buy them at the lodge bar or at the local restaurant."
    NoIncluye3.innerText="Tips: Tips for guides and lodge staff are not included in the package price. It is recommended to tip 10% to 15% of the total value of the package as a token of appreciation for their service."
    NoIncluye4.innerText="Personal expenses: Personal expenses such as souvenirs, telephone calls, laundry, etc., are not included in the package price."
    NoIncluye5.innerText="Seguro de viaje: Se recomienda contratar un seguro de viaje que cubra gastos médicos, cancelación de vuelos y pérdida de equipaje."
    
    var Importante=document.getElementById("Importante")
    var Importante1=document.getElementById("Importante1")
    var Importante2=document.getElementById("Importante2")
    var Importante3=document.getElementById("Importante3")
    var Importante4=document.getElementById("Importante4")

    Importante.innerText="Important"
    Importante1.innerText="The trip itinerary may be subject to change due to weather conditions, transportation availability or for other unforeseen reasons."
    Importante2.innerText="It is important to wear clothing and footwear appropriate for the weather and the activities to be carried out."
    Importante3.innerText="It is recommended to bring sunscreen, mosquito repellent, a hat and sunglasses."
    Importante4.innerText="It is important to respect the rules of the national park and help protect the environment."


   var QuePermi=document.getElementById('QuePermi')
   
   QuePermi.innerText="What is allowed and prohibited in the Pumalín Douglas Tompkins National Park?"

   var Permitido=document.getElementById('Permitido')
   var Permitido1=document.getElementById('Permitido1')
   var Permitido2=document.getElementById('Permitido2')
   var Permitido3=document.getElementById('Permitido3')
   var Permitido4=document.getElementById('Permitido4')
   var Permitido5=document.getElementById('Permitido5')
   var Permitido6=document.getElementById('Permitido6')
   var Permitido7=document.getElementById('Permitido7')
   var Permitido8=document.getElementById('Permitido8')

   Permitido.innerText="Allowed"
   Permitido1.innerText="Go hiking and trekking along the marked trails."
   Permitido2.innerText="Kayak or canoe through the fjords and lakes (with permission)."
   Permitido3.innerText="Fishing in rivers and lakes (with permission)."
   Permitido4.innerText="Observe the flora and fauna."
   Permitido5.innerText="Camp in designated areas."
   Permitido6.innerText="Bring enough food and drink for the excursions."
   Permitido7.innerText="Use sunscreen and mosquito repellent."
   Permitido8.innerText="Wear clothing and footwear appropriate for the weather and the activity to be carried out."

   var Prohibido=document.getElementById('Prohibido')
   var Prohibido1=document.getElementById('Prohibido1')
   var Prohibido2=document.getElementById('Prohibido2')
   var Prohibido3=document.getElementById('Prohibido3')
   var Prohibido4=document.getElementById('Prohibido4')
   var Prohibido5=document.getElementById('Prohibido5')
   var Prohibido6=document.getElementById('Prohibido6')
   var Prohibido7=document.getElementById('Prohibido7')
   var Prohibido8=document.getElementById('Prohibido8')
   var Prohibido9=document.getElementById('Prohibido9')
   var Prohibido10=document.getElementById('Prohibido10')
   var Prohibido11=document.getElementById('Prohibido11')

   Prohibido.innerText="Forbidden"
   Prohibido1.innerText="Leave the marked trails."
   Prohibido2.innerText="Make campfires outside of designated areas."
   Prohibido3.innerText="Cause damage to the flora or fauna of the park."
   Prohibido4.innerText="Pollute water or soil."
   Prohibido5.innerText="Entering non-permitted areas with motorized vehicles."
   Prohibido6.innerText="Disturb wildlife."
   Prohibido7.innerText="Extract flora or fauna from the park."
   Prohibido8.innerText="Use drones without prior authorization."
   Prohibido9.innerText="Carry out noisy activities that may disturb the tranquility of the park."
   Prohibido10.innerText="Camping in non-designated areas."
   Prohibido11.innerText="Leaving trash in the park."

   var Recuerda=document.getElementById('Recuerda')
   var Recuerda1=document.getElementById('Recuerda1')

   Recuerda.innerText="Remember!"
   Recuerda1.innerText="Your responsible behavior will help protect this valuable natural heritage for future generations."

}